### ISSUE TITLE
Runtime error about metis 

### ISSUE THREAD

**Issue by ByskyXie** [benedekrozemberczki/ClusterGCN#17]
At the train begining that part the full graph, the function "metis.part_graph(self.graph, self.args.cluster_number)" throws an error:
`
Traceback (most recent call last):
  File "C:/Users/xieRu/Desktop/ML/ClusterGCN/src/main.py", line 30, in <module>
    main()
  File "C:/Users/xieRu/Desktop/ML/ClusterGCN/src/main.py", line 19, in main
    clustering_machine.decompose()
  File "C:\Users\xieRu\Desktop\ML\ClusterGCN\src\clustering.py", line 38, in decompose
    self.metis_clustering()
  File "C:\Users\xieRu\Desktop\ML\ClusterGCN\src\clustering.py", line 56, in metis_clustering
    (st, parts) = metis.part_graph(self.graph, self.args.cluster_number)
  File "D:\Program\Anaconda\lib\site-packages\metis.py", line 800, in part_graph
    _METIS_PartGraphKway(*args)
  File "D:\Program\Anaconda\lib\site-packages\metis.py", line 677, in _METIS_PartGraphKway
    adjwgt, nparts, tpwgts, ubvec, options, objval, part)
OSError: exception: access violation writing 0x000001B0B9C0E000
`

But I tried test package metis as follow, It works:
`
import metis
from networkx import karate_club_graph

zkc = karate_club_graph()
graph_clustering=metis.part_graph(zkc)
`
So, what happend?

**Comment by benedekrozemberczki** [comment]
It is not particularly scalable.
